// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH1MOoloM2HsIuv2aNHLK2lmLMJlkhpDs',
    appId: '1:66446307385:web:9e473df96d910a2fcf9de8',
    messagingSenderId: '66446307385',
    projectId: 'campis-462e5',
    authDomain: 'campis-462e5.firebaseapp.com',
    storageBucket: 'campis-462e5.firebasestorage.app',
    measurementId: 'G-Q4NCHZPWS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtEknk0kXS2uLS5Y8PWio8W-n7KtnkQTs',
    appId: '1:66446307385:android:de1cf95ad2adc11fcf9de8',
    messagingSenderId: '66446307385',
    projectId: 'campis-462e5',
    storageBucket: 'campis-462e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh4vBrd_r5YGpJn4dbvzHeC9bSpLmvNng',
    appId: '1:66446307385:ios:5bce8a81e054a133cf9de8',
    messagingSenderId: '66446307385',
    projectId: 'campis-462e5',
    storageBucket: 'campis-462e5.firebasestorage.app',
    iosBundleId: 'com.project.cc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh4vBrd_r5YGpJn4dbvzHeC9bSpLmvNng',
    appId: '1:66446307385:ios:5bce8a81e054a133cf9de8',
    messagingSenderId: '66446307385',
    projectId: 'campis-462e5',
    storageBucket: 'campis-462e5.firebasestorage.app',
    iosBundleId: 'com.project.cc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH1MOoloM2HsIuv2aNHLK2lmLMJlkhpDs',
    appId: '1:66446307385:web:0b29c8b7da5022a3cf9de8',
    messagingSenderId: '66446307385',
    projectId: 'campis-462e5',
    authDomain: 'campis-462e5.firebaseapp.com',
    storageBucket: 'campis-462e5.firebasestorage.app',
    measurementId: 'G-1CLMVCYM9H',
  );
}
